# Generated by Django 5.0.7 on 2024-08-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0002_assignment_transcription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="reference_text",
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="transcription.assignment",
                    ),
                ),
            ],
        ),
    ]
