# Generated by Django 5.0.7 on 2024-08-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0003_remove_assignment_reference_text_questionanswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcription",
            name="reference_text",
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="answer",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="question",
            field=models.TextField(max_length=500),
        ),
        migrations.DeleteModel(
            name="ReferenceText",
        ),
    ]
