# Generated by Django 5.0.7 on 2024-08-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0004_remove_transcription_reference_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_codes",
                        to="transcription.assignment",
                    ),
                ),
            ],
        ),
    ]
