# Generated by Django 5.0.7 on 2024-08-17 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0005_classcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="answer",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="question",
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("french_word", models.CharField(max_length=100)),
                ("english_translation", models.CharField(max_length=100)),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="transcription.flashcardset",
                    ),
                ),
            ],
        ),
    ]
