# Generated by Django 5.0.7 on 2024-08-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0006_flashcardset_alter_questionanswer_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardset",
            name="bulk_flashcards",
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="english_translation",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="french_word",
            field=models.CharField(max_length=200),
        ),
    ]
